### ISSUE TITLE
Suggestion- VU Improvements

### ISSUE THREAD

**Issue by Spider-07** [InZidiuZ/op-framework-issue-tracker#2427] opened 2022-08-07 14:57 UTC
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?

yes

**Summary:**
Write a summary of what your suggestion is about.

Another thing is that the main door is always open after restarting the server, so it is better to keep this door closed. And everyone can use this bar shop but it would be better if it is made in such a way that only bar staff can use it. 

It would be better to increase the salary a little. 

No soft drinks and snacks here. There are many people who don't drink alcohol, they want soft drinks, snacks so adding some soft drinks is better.

**Reason:**
Why would your suggestion be a good change to the framework?

We think doing the above can generate a lot more RP with vanilla unicorns.

![pngwing com (3)](https://user-images.githubusercontent.com/103858728/183296850-503ac0e0-4515-408b-9d05-5202f141c0d3.png)
![pngwing com (2)](https://user-images.githubusercontent.com/103858728/183296856-af399a8b-b12a-440d-84c0-e4002dbbedbd.png)
![pngwing com (1)](https://user-images.githubusercontent.com/103858728/183296857-8005e5ba-e5db-4dc7-a8ed-2e20c9a930ba.png)
![pngwing com (4)](https://user-images.githubusercontent.com/103858728/183296863-662b1d8b-40d7-4407-b427-83481ee9a83a.png)
![pngwing com](https://user-images.githubusercontent.com/103858728/183296865-8a185867-c5ed-4b4c-adef-d5f4aff1eef9.png)

![pngwing com (5)](https://user-images.githubusercontent.com/103858728/183296873-0dfd0689-6403-4055-8a40-525a25aedefc.png)
![pngwing com (7)](https://user-images.githubusercontent.com/103858728/183296881-dd90ef81-ebb6-4bc5-be26-cdb2c77f7087.png)
![pngwing com (8)](https://user-images.githubusercontent.com/103858728/183296896-30f92b6b-de94-4396-baba-d5603aa592ba.png)
![pngwing com (9)](https://user-images.githubusercontent.com/103858728/183296900-8ba13b4a-e2e3-4232-a1a9-0a48ff3b0ac5.png)
![download](https://user-images.githubusercontent.com/103858728/183297107-244a5cf0-8781-42ae-a787-27871ebd61c7.jpg)
![pngegg (1)](https://user-images.githubusercontent.com/103858728/183297111-4c106307-62a8-490e-b92d-4360451a931a.png)
![pngegg (5)](https://user-images.githubusercontent.com/103858728/183297119-5a4b0df1-8d73-43aa-8945-ba72f8240591.png)
![pngegg (4)](https://user-images.githubusercontent.com/103858728/183297120-e70f56c1-b4f6-47fe-9239-b6886f91798b.png)
![pngegg (3)](https://user-images.githubusercontent.com/103858728/183297122-df32a4fa-f3d7-4092-9b52-40947a8ca31e.png)
![pngegg](https://user-images.githubusercontent.com/103858728/183297128-3784fff3-e4bf-477c-8fa6-0db52ba714af.png)

**Comment by twooot** [comment] 2022-08-15 09:14
closing as its pretty much a duplicate of #2437

**Closed by twooot** 2022-08-15 09:14 UTC
Labels: suggestion
