### ISSUE TITLE
Trunk bulk match vehicle class

### ISSUE THREAD

**Issue by N8teZero** [InZidiuZ/op-framework-issue-tracker#142] opened 2019-07-01 20:39 UTC
**Reporter:**
Nate

**Summary:**
Certain vehicles have trunk space that shouldn't, such as dirtbikes and motorcycles.

**Expected Results:**
Vehicles with no physical means to store items, should have no virtual trunk space.

**Comment by InZidiuZ** [comment] 2019-07-02 01:15
Hey,

Although not a bug, as I never attempted to prevent this, I will probably do something about this as I've been thinking about it for quite some time. Only issue would be people already having items stored in these inventories.

Was also thinking I wouldn't remove it entirely, but just lower it to 50 bulk on bikes, instead of 400, and make the bulk amounts match the different vehicles a bit more.

**InZidiuZ**
*OP-FW Developer*

**Comment by SteezyRen** [comment] 2019-07-04 02:05
Is there a way that if there is a nerf to their vehicle storage that they just can't drive the vehicle until the weight has been brought down to levels that no longer encumber their vehicles?

If not, just make an announcement regarding vehicle storages before implementing and recommend everyone to clear vehicle inventory or minimizing inventory in vehicles before a patch is in place so people will have ample time to clear.

**Comment by InZidiuZ** [comment] 2019-07-05 16:21
A notice would be made, @SteezyRen.

Anyways, will close this as it's the same as #150.

**Closed by InZidiuZ** 2019-07-05 16:21 UTC
Labels: enhancement
