### ISSUE TITLE
All of southside garages are broken, they only work sometimes Bug report reopen

### ISSUE THREAD

**Issue by eBoiBuns** [InZidiuZ/op-framework-issue-tracker#1908] opened 2021-07-04 21:01 UTC
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
yup
**Player Identification:**
What is your steam profile?
https://steamcommunity.com/profiles/76561198079064773/
**Summary:**
Write a short summary of what you are experiencing.
Garages only work sometimes work in the south side
i want to be able to use the garage I pay for
without spending at least double on retrieving my vehicles

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
try and use garage. mostly the garage at your house which you pay 6000$ a week to use. (old SSK block in particular)
**Expected Results:**
What are the expected results?
it will either spawn a local whip that everyone else but you can see or vice versa.
if it's invisible for the user of the garage, they must hard nap.
if they can see the local whip, they can retrieve their vehicle and and repeat.
**Actual Results:**
What are the actual results?
good question
## Additional Information
t is unplayable for me. i join into the city, expecting to be able to chill, and use my house/garage only for me to waste $500 -1000$ then proceed to look for a ride to a different garage. it makes me not want to do anything. on top of me grinding my ass off everyday, this is just completely demoralizing. completely gets rid of my desire to continue to progress.
ive also noticed that the garages work less and less the closer we get to tsunami (same goes for selling drugs, and diving)
you become less efficient as the day progresses (my guess is the server can't handle the load)
a quick fix would be to have an extra tsunami to balance it out (a tsunami every 12 hours)
**Screenshots:**
If suitable, include some screenshots.
https://gyazo.com/63c40ccb3763616087bb330ab90f9da8

https://www.youtube.com/playlist?list=PLOop0WzYKCnPww11HNszU0Cq1WS9kUaz4

https://i.gyazo.com/thumb/1200/49f540dc33c4907608aeba4fa24cc81b-png.jpg
**Game Resolution:**
What is your game's resolution?
2560x1440
**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.

**Server:**
What server/community did this issue occur in?
Legacy Roleplay EU/NA
**Notes:**
For anything else noteworthy.
other Bug report https://github.com/InZidiuZ/op-framework-issue-tracker/issues/1869

**Comment by FullMetalAlphonse** [comment] 2021-07-04 21:11
I am having the same issue, I can only very rarely pull a vehicle out of the garage without it spawning as a local copy (rarely meaning MAYBE once or twice a week)

**Comment by InZidiuZ** [comment] 2021-07-05 08:25
I just tried reproducing it on the live server, and here's the [result](https://gyazo.com/483175c284a6b300dbbdfcdbe6c066aa). How much ping do you play with? I also see that the videos you linked are very laggy, perhaps it could have something to do with that.

This was done when the server had been up for 22 hours, so I have a hard time believing it would have anything to do with the server's uptime. The server was only half-full, so I can test again when it is full.

**Comment by eBoiBuns** [comment] 2021-07-06 08:52
if it has to do with connection, can you please explain why those specific garages are the only ones with issues? and why there are so many people with the same issue.

**Comment by InZidiuZ** [comment] 2021-07-06 08:57
All the garages are the same. When a vehicle is created, the server assigns ownership of that vehicle to a player, and since you most likely are the closest player you are most likely to be the player it picks. Here it seems that it is either really delayed or it bugs out, causing it to not have its data applied (modifications, plate number, etc.) as that still has to be handled by a player's client. 

I'm not sure, but perhaps due to lag or high ping the server tries to pick another nearby player, but as that player doesn't receive the same instructions as you would have, they're never applied. Or maybe you are given the ownership, but not fast enough for when your client tries to apply the data. Not sure... more info would be nice.

**Comment by eBoiBuns** [comment] 2021-07-06 21:16
but that still does not answer why every other garage works without issue. any clue?

**Comment by InZidiuZ** [comment] 2021-07-07 06:14
There is no reason for that like I said, so that most likely isn't the case. If you decided to use another garage with the same amount of people and NPCs nearby, you'd most likely experience the same there. There's no difference between the garages, they all run on the same exact code.

**Comment by eBoiBuns** [comment] 2021-07-07 18:56
alright, so what I'm understanding is; the server cannot handle the amount of activity in the south side. I do not believe ping is  a very big factor as I have met EU players with 28 ping who experience the same issues, my most recent encounter with an eu player today.

**Comment by InZidiuZ** [comment] 2021-07-08 12:28
It's not that it can't handle the activity, rather that it potentially picks someone else & ping *could* be a factor, or anything else that could make the server deem your client unavailable. I added some debugging to help figure out what is exactly happening. On next update (live servers usually only update on Tuesdays), do `/toggle_garage_debug` in the chat to enable this. Whenever you pull out a vehicle, it'll then give you some information in the F8 console that looks like [this](https://gyazo.com/b68236fbbc0ee73d8641555e3d627797).

Next time this happens and you manage to get ahold of that data, please post a picture of it here so I can further look into it.

**Comment by eBoiBuns** [comment] 2021-07-09 18:12
Please allow me a couple days to test it out.

**Comment by InZidiuZ** [comment] 2021-07-14 09:40
Have you managed to get any data?

**Comment by eBoiBuns** [comment] 2021-07-15 19:15
So the garages seem to have been working a lot better since the Fivem update. idk why. They do still scuff occasionally, but I don't think I can complain at this point. If you keep this thread open, ill get the debug info today or tmr.

**Comment by eBoiBuns** [comment] 2021-07-17 17:49
So the original issue seems to have been resolved or replaced by a new bug. storing vehicles sometimes duplicates them. but hey, at least our garages work now!

**Comment by lolayygaming** [comment] 2021-07-18 02:37
https://gyazo.com/aa10c9195bd63ba53330aa111f8156d4 https://clips.twitch.tv/ArborealShyStinkbugYee-ZeGevLAMAbyrUOQG

**Comment by Detnom** [comment] 2021-07-18 02:38
https://streamable.com/cety7u

**Comment by twooot** [comment] 2022-01-23 21:22
i'm pretty sure a lot of garage related issues have since been fixed with the recent updates

**Comment by InZidiuZ** [comment] 2022-04-09 19:03
Will be closing this. A lot of improvements have been made to spawning of vehicles which should help prevent this. More fixes and improvements are continually being made, too, but it has proven to be very problematic.

**Closed by InZidiuZ** 2022-04-09 19:03 UTC
Labels: bug, feedback/discussion needed
