### ISSUE TITLE
PDM Finance

### ISSUE THREAD

**Issue by Sleezybeezy** [InZidiuZ/op-framework-issue-tracker#230] opened 2019-07-19 09:58 UTC
![SS2](https://user-images.githubusercontent.com/50811631/61528233-39e20300-a9ec-11e9-8cfd-b482919fb477.png)
![SS](https://user-images.githubusercontent.com/50811631/61528175-17e88080-a9ec-11e9-87f2-7225af1e6b2c.png)
**Reporter:**
Beezy#6584     steam username SleezyBeezy

**Summary:**
Typed my /finances and appeared with my car payment i owe, i type /finance (ID) and it paid my finance i owed but when i entered /finances to make sure it paid, it still says i owed. I know i dont owe a double payment or anything as i paid my last weeks. Just didnt want to pay again and be out more money if it was a bug.

**Steps to Reproduce:**
I haven't tried to replicate by attempted to pay again as my logs should show i made the cash payment as it was deducted from my account.

**Expected Results:**
Expected results would be me typing /finances and nothing popping up because i shouldn't owe anything.

**Actual Results:**
when i type /finances it still shows my current car plate number, ID and what i owe even though i've paid it.

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
1920 x 1080

**Player Data:**
Character ID: 1628 - Job Data: Mechanic, Los Santos Customs, Tow Driver
Timestamp: 2019-07-19  10:56:47

**Notes:**
I have illegal drugs and a tuner chip in my car so i would like to not lose it due to finances is why i'm so worried about it.

**Comment by AmokBSN** [comment] 2019-07-19 12:27
I tried mines yesterday (paid 2000 towards) still remained 2000. I don't have any screenshots, unfortunately.

**Comment by AdeptCL** [comment] 2019-07-19 12:30
Same here when I paid $6,750 + $1,250 on two cars.

**Comment by InZidiuZ** [comment] 2019-07-19 12:48
Hey,

There was a bug with the finances only making you pay for the first week, so everyone had a maximum of **1** completed finance transaction, which means all the missed ones are now appearing. Keep paying them until you don't get it anymore, then you will be update. Closing as this is not a bug.

**InZidiuZ**
*OP-FW Developer*

**Closed by InZidiuZ** 2019-07-19 12:48 UTC
Labels: bug
