### ISSUE TITLE
Suggestion - winery making for Marlowe vineyard 

### ISSUE THREAD

**Issue by Xorosexo** [InZidiuZ/op-framework-issue-tracker#2787] opened 2023-05-10 17:10 UTC
### Assurance

I have read the `README.md`

### Summary

-I’ve heard that before in the city Marlowes vineyard had a wine making mod where you can harvest and make your own wine and sell it. I was wondering if something like that can be brought back again 

### Reason

-if this were to be brought back it would bring lots more revenue for my wedding/party business to wear I can provide my own alcohol and provide advertising for my business and the vineyard and would bring in more rp to add more employees as well

**Comment by coalaura** [comment] 2023-05-11 23:08
Closing as somewhat duplicate of this #2088

**Closed by coalaura** 2023-05-11 23:08 UTC
Labels: suggestion
