### ISSUE TITLE
Suggestion - Wallet for IDs

### ISSUE THREAD

**Issue by Dibbey** [InZidiuZ/op-framework-issue-tracker#2932] opened 2023-08-27 12:53 UTC
### Assurance

I have read the `README.md`

### Summary

Alright, so this might be a long-shot and really only for people that do end up getting a lot of IDs or licenses.
So there's currently multiple available IDs in the city:
- Citizen ID
- EMS / PD and other job IDs
- Hunting License
- Mining License
- Pilot License
- Weapon License
- (Fishing License once public)

So what if you had something that works similarly to the Backpack but it's a Wallet and you can **ONLY** put IDs and licenses in it. 

### Reason

Due to the amout of licenses, when carrying them with you (Although you are not forced to carry them all 24/7), it can clog up your pockets to the point where multiple slots are taken up.

It would really only be a QoL idea that would allow people to not lose their IDs somewhere in a trunk/locker/storage to free up space then having to buy a new one or when moving around items/carrying multiple other items struggle with free pocket space.

**Comment by TheOneLizard** [comment] 2023-08-27 13:02
https://github.com/InZidiuZ/op-framework-issue-tracker/issues/2461

(also the hunting license covers fishing too)

**Comment by Dibbey** [comment] 2023-08-27 13:20
Damn, the search function did me dirty. My bad for duplicate post, sorry!

**Comment by coalaura** [comment] 2023-08-27 13:38
Duplicate of #2461

**Closed by coalaura** 2023-08-27 13:38 UTC
Labels: suggestion
