### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by KillaCorn** [InZidiuZ/op-framework-issue-tracker#477] opened 2019-10-06 12:36 UTC
**Reporter:**
KiLLaCORN#2395
https://steamcommunity.com/profiles/76561198145466675/
**Summary:**
When i run coke mission then get back in my car it will not move.

**Steps to Reproduce:**
-Park Car Next To Hanger.
-Run Coke Mission.
-Get Back In Car And Will Not Move.

**Expected Results:**
The Car Would Continue To Work.

**Actual Results:**
Car Does Not Move

## Additional Information

**Game Resolution:**
1920x1080

**Player Data:**
300
**Notes:**
Can provide Vid if you would like.

**Comment by InZidiuZ** [comment] 2019-10-06 12:51
Provide video.

**Comment by HridayHS** [comment] 2019-10-06 13:44
I will proivde video in a bit once I get the chance to get the plane (It's pretty hard in Indian servers to get one).

Also to mention,
1. If you don't have a car and you complete the coke mission and then if you hijack NPC's car, it will also be scuffed and won't move. (But the next hijacked car will work fine).
2. Sometimes car won't scuff but the brake fails.

**Comment by KillaCorn** [comment] 2019-10-06 14:11
https://plays.tv/video/5d99f4fa24b0fa5c7a/coke-plan-bug   @InZidiuZ

**Comment by InZidiuZ** [comment] 2019-10-06 16:12
Hey,

Just finished rewriting the tuner-chip, which I believe is the cause for this. After next update, see if this continue to happen. I'll keep this open till it's (un)confirmed this is no longer an issue.

**Comment by InZidiuZ** [comment] 2019-10-06 18:48
This is apparently no longer an issue, so closing.

**Closed by InZidiuZ** 2019-10-06 18:48 UTC
Labels: bug
