### ISSUE TITLE
Bug report ( /admin Crash some time )

### ISSUE THREAD

**Issue by ravicant** [InZidiuZ/op-framework-issue-tracker#1509] opened 2020-11-09 19:19 UTC
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Player Identification:**
What is your steam profile?
https://steamcommunity.com/id/RaviCant1/
**Summary:**
Write a short summary of what you are experiencing.
So Basically when you spectate people if they are in a house or something like that for client /admin get a crash
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
It happens randomly 
**Expected Results:**
What are the expected results?
it should not crash
**Actual Results:**
What are the actual results?
its crashing
## Additional Information
No
**Screenshots:**
If suitable, include some screenshots.
https://i.ravicant.in/pwuDxv1O0
**Game Resolution:**
What is your game's resolution?
1920x1080
**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.

**Server:**
What server/community did this issue occur in?
Legacy Roleplay India Public
**Notes:**
For anything else noteworthy.

**Comment by GuArDiAn-ops** [comment] 2020-11-09 19:55
https://gyazo.com/2865d853c4328534ee0cc8566db6a5bf
Happens randomly someone you are spectating goes inside the house.

**Comment by glocknine234** [comment] 2020-11-09 19:56
When you spectate someone who's in the house it looks like he's under the city and you can't see his body.

**Comment by InZidiuZ** [comment] 2020-11-10 23:47
I tried reproducing this issue but was not able to. Could you provide a video of this happening, or some more details as to how to repro it? I tested with my client spectating another player that entered another house near the Grove Street area, but no 'crashes' or errors occurred.

> When you spectate someone who's in the house it looks like he's under the city and you can't see his body.

That's not going to be fixed. The player is under the map and I probably won't make shells spawn in for spectating admins in the near future, if ever.

**Comment by KaliaaAndy** [comment] 2020-11-11 08:13
Hello all My cars mod has been gone 😭!! EDM cars they was. 
![IMG-20201111-WA0022](https://user-images.githubusercontent.com/74291722/98786107-a2e05c00-2423-11eb-9bd0-0c4c333bfcb4.jpg)
![IMG-20201111-WA0024](https://user-images.githubusercontent.com/74291722/98786113-a542b600-2423-11eb-88d8-184373bbc1e9.jpg)
![IMG-20201111-WA0025](https://user-images.githubusercontent.com/74291722/98786118-a5db4c80-2423-11eb-846a-673900b275fa.jpg)
![IMG-20201111-WA0028](https://user-images.githubusercontent.com/74291722/98786122-a673e300-2423-11eb-8439-c256d41b947c.jpg)
![IMG-20201111-WA0030](https://user-images.githubusercontent.com/74291722/98786125-a70c7980-2423-11eb-8434-3275e2466b06.jpg)
![IMG-20201111-WA0033](https://user-images.githubusercontent.com/74291722/98786128-a7a51000-2423-11eb-8544-ee99028fb16e.jpg)
![IMG-20201111-WA0034](https://user-images.githubusercontent.com/74291722/98786132-a8d63d00-2423-11eb-8bed-ed3eb1a31990.jpg)
![IMG-20201111-WA0035](https://user-images.githubusercontent.com/74291722/98786133-a96ed380-2423-11eb-8061-55a465062aff.jpg)
![IMG-20201111-WA0037](https://user-images.githubusercontent.com/74291722/98786134-aa076a00-2423-11eb-8ef5-9d33f75c0d30.jpg)
![IMG-20201111-WA0040](https://user-images.githubusercontent.com/74291722/98786138-aaa00080-2423-11eb-8425-616ad0df36bf.jpg)
![IMG-20201111-WA0039](https://user-images.githubusercontent.com/74291722/98786139-abd12d80-2423-11eb-847d-fb32c6ea039a.jpg)
![IMG-20201111-WA0029](https://user-images.githubusercontent.com/74291722/98786141-ac69c400-2423-11eb-9d62-72d931246345.jpg)
![1605082320582193580036714801580](https://user-images.githubusercontent.com/74291722/98786151-b1c70e80-2423-11eb-90c3-0c7d1c001927.jpg)
![16050823517729087776347351907005](https://user-images.githubusercontent.com/74291722/98786197-c3101b00-2423-11eb-8617-230468b0a327.jpg)



My all Mods are gone all were maxed

**Comment by AdeptCL** [comment] 2020-11-11 08:14
This has absolutely nothing to do with the /admin issue that was raised.

**Comment by ravicant** [comment] 2020-11-11 08:23
> I tried reproducing this issue but was not able to. Could you provide a video of this happening, or some more details as to how to repro it? I tested with my client spectating another player that entered another house near the Grove Street area, but no 'crashes' or errors occurred.
> 
> > When you spectate someone who's in the house it looks like he's under the city and you can't see his body.
> 
> That's not going to be fixed. The player is under the map and I probably won't make shells spawn in for spectating admins in the near future, if ever.

Ya here you go :- https://youtu.be/ohXwlPWMxds?t=11190

**Comment by GuArDiAn-ops** [comment] 2020-11-11 18:20
Try this have someone on spectate and as soon as they walk into the house it happens or any kind of door with the enter animation even LSC if you spectate someone upgrading a vehicle it doesnt show anything just crashes.

**Comment by InZidiuZ** [comment] 2020-11-11 20:22
This issue should be resolved with version 3279.

**Closed by InZidiuZ** 2020-11-11 20:22 UTC
Labels: bug, feedback/discussion needed
