### ISSUE TITLE
Suggestion - Burger Shot 

### ISSUE THREAD

**Issue by selliee** [InZidiuZ/op-framework-issue-tracker#2681] opened 2023-02-24 05:37 UTC
### Assurance

I have read the `README.md`

### Summary

Hello, I am here suggesting some changes be made to help enhance the RP experience not only for Burger Shot, but other food businesses as well. Majority of my suggestion will be aimed towards some changes at Burger Shot to help make it a place where people would like to RP as a worker and also as a customer. 

First, let me get out of the way the ultimate problem that has been discovered, the Arcade. Now, hear me out. Not only can you buy food from the Arcade, but what the big attraction to it is the obvious, Z pills. Now, the problem with Z pills which I have discussed amongst multiple people within the server & other businesses is that Z pills give you food. That takes away from people needing to go anywhere to actually have an interaction besides when they purchase the z pills. 

Along with z pills giving food- the cost/what employees make off of them. Businesses such as Burger Shot, Bean Machine, and I could possibly speak for every other business within the city, has probably had people leave to go work at the Arcade simply because someone can make $600 off of a singular Z pill- and the max someone can "use" daily is 25? 

My suggestion for Z pills would be PLEASE.. PLEASE.. PLEASEEE.. remove all food items!! Maybe make it also so people don't make so much off of z pills so other businesses look enticing as well without us having to up the price of our food (burger shot bags are already $200 and employees only profit around $130 ish from it). Upping food prices will make people just go and buy tacos and cokes from the stores.

Meanwhile Burger shot is what I believe to be, the only establishment where employees have to craft their food, taking up time that customers don't want to wait for! I have had a lot of employees tell me that they have customers literally walk out while making their food because it takes so long to make the meals. PD orders in bulk, up to 50 meals sometimes.. 4 patties are in 1 meal. My suggestion would be to let us grill 4 patties at once! The grill in the establishment is def big enough to "rp out grilling 4 patties at once". 

Burger Shot's food has also gotten its special effects taken away, meanwhile other establishments have not. One thing that really helped our sales and increasing interactions was the fact that our food relieved stress. I suggest putting this back into at least the french fries. 

Other things that will enhance RP and driving traffic / employment:

- Actual Burger shot food .. I have the icons/food for the real menu items
- We need an actual LOCKER put into the employee break room for staff to store stuff.
- Put in a hot bar next to where you bag the food to help keep freshness of food for employees who work long shifts
- I would love to have a menu put in kind of like the brochure, where we can hand out at the counter for civs to look at with a image of the burger shot menu. I believe this could create some fun RP by giving special names to meals, creating custom meals, and having real pricing on the menu so we dont have to constantly put down note pads. it will also help us with having a dine in RP aspect too.
- Please please please the invisible barrier above the counter.. make it so we can see /me and paypals again. I had a person who was mute, she had to quit burger shot because she was unable to RP as such, and do her sign language.
- change the pay out for deliveries, and have a cool down period in between deliveries so it doesnt get abused. 

### Reason

I believe that my suggestions would be good not just for the framework but for the city because it will enhance RP.. Which, is the whole point of the server. 

-Get rid of food from Z pills so people actually have to interact with people at a restaurant.
-Lower the Z pill financial gain as an employee & the pill itself all together so people will stop grinding them & actually RP.
-Either greatly shorten the time it makes to grill a patty or make it so we can grill 4 at once to enhance RP "this is a fast food establishment but my order is taking forever!!" - real quote from multiple customers 2022
-Put back the stress relieving effects of the food.
-Having actual menu items that suit the burger shot menu and whats advertised will greatly enhance RP!! yes, this includes ice cream. (I can provide these)
- Lockers for staff
- Hot bar for food freshness for people who want to keep food fresh and RP that
- A cool Menu to enhance RP inside the store and also could be used to entice employees to go around the city to draw customers in! Also great for parties hosted outside of the establishment.
- Fix not being able to see paypals and also /me's behind the counter. 
- I would love to up the price of deliveries. I know this is a sticky one.. people have abused it in the past, yes. But it also brought traction to the store.

These things will greatly enhance the experience, and ultimately the Z pill thing I believe will also help other businesses who are struggling and just dont feel like they will be heard if they submit a github about it[yes this is in fact a real thing]. 

Thank you for your time

**Comment by RubanioBoi** [comment] 2023-02-24 05:41
Both Burgershot and bean Machine desperately need something to help the business actually bring in costumers. because in my honest opinion people will flood to the spot that they can grind out and make the most money, doesn't matter if it has Rp behind it or not so there really needs to be something that can help in any way possible

**Comment by spitslave** [comment] 2023-02-24 05:57
I love these ideas, I also want for people to start dining in as well, so it would be cool to see more items on the menu where people can come and order.
I think this would be really good for burgershot and RP overall.

**Comment by PedroTheTurtle** [comment] 2023-02-24 05:59
I completely agree with this. At Bean Machine we have been struggling with attracting new workers since the introduction of z-pills at the Arcade. People know that running zpills yields great profit and we had many employees leave just so they could start doing zpills as a full-time job The profit made from selling food to others in the city is so small compared to what could be made through the pills that I have not found anyone that genuinely wants to work at Bean. Any new hires we have had only stay to grind local deliveries until they have enough money for zpills and then they leave. Trying to attract customers and new employees has become so disheartening that Jasmin and I have started to look for someone else to take over Bean. We have lost our joy in running the business since people rarely come to buy our food and no one seems to want to work for us anymore.

**Comment by selliee** [comment] 2023-02-24 06:10
> I completely agree with this. At Bean Machine we have been struggling with attracting new workers since the introduction of z-pills at the Arcade. People know that running zpills yields great profit and we had many employees leave just so they could start doing zpills as a full-time job The profit made from selling food to others in the city is so small compared to what could be made through the pills that I have not found anyone that genuinely wants to work at Bean. Any new hires we have had only stay to grind local deliveries until they have enough money for zpills and then they leave. Trying to attract customers and new employees has become so disheartening that Jasmin and I have started to look for someone else to take over Bean. We have lost our joy in running the business since people rarely come to buy our food and no one seems to want to work for us anymore.

I agree with the last bit! I have kept Nia clean for over a year because there was joy in Rping as a owner- but now theres barely any RP  with this business as a "boss" because you have employees who don't want to work/rp and its hard finding people who will stay for longer than a week.

**Comment by xEleyna** [comment] 2023-02-24 06:25
I agree to basically all of the above. I was enjoying the first few months of being bean machines owner. But lately it’s just tiring. Nobody comes in, nobody orders, nobody wants to work there.
 I also believe the arcade should fully stop selling food honestly, or have them sell popcorn only, nothing else. It’s an arcade and not a food place, and they make enough money with being the only place to buy z pills. Big monopoly on that. Lately I see them tell people and advertising on twitter that they’re delivering food and people can come in buy food. Not advertising for the games at all which of course takes away the customers off of the pure food businesses which is frustrating for us. Who wants to work behind a counter hoping somebody comes in within the next few hours and the only person that comes in leaves while preparing the food that the employee already payed for?

**Comment by selliee** [comment] 2023-02-24 06:31
> I agree to basically all of the above. I was enjoying the first few months of being bean machines owner. But lately it’s just tiring. Nobody comes in, nobody orders, nobody wants to work there. I also believe the arcade should fully stop selling food honestly, or have them sell popcorn only, nothing else. It’s an arcade and not a food place, and they make enough money with being the only place to buy z pills. Big monopoly on that. Lately I see them tell people and advertising on twitter that they’re delivering food and people can come in buy food. Not advertising for the games at all which of course takes away the customers off of the pure food businesses which is frustrating for us. Who wants to work behind a counter hoping somebody comes in within the next few hours and the only person that comes in leaves while preparing the food that the employee already payed for?

So, I do too, agree that removing food from the arcade is probably something that should happen as well. And I do agree that RP wise, its weird they are offering delivery- when its an arcade and I believe that they were denied deliveries [dont quote me], in the phone- because .. they are an arcade! I believe that some work might need to be put into the arcade to make it better as an ARCADE.. and for now, the only RP the workers really can get out of it is selling z pills, arena pills and food. Yes theres games there but IMO they arent super special. 

I do agree though. It is hard, and something has to change ultimately to make these establishments better

**Comment by selliee** [comment] 2023-02-24 06:36
Id also like to add this since I forgot to mention it: yes we have a burger shot VAN.. but everyone would really appreciate a car! to do deliveries in.. local and civ. Bean machine has a car that is great for deliveries. They dont have to pay for repairs or gas. Burger Shot employees have the option for the van but its just not a fan favorite, so they end up using their personal vehicles and end  up having to pay for repairs and gas which with the low-paying deliveries, can sometimes be half if not, most of what they make in their deliveries they do

**Comment by scufflord** [comment] 2023-02-24 07:34
I wanted to touch on the local deliveries real quick and went and did 1 full hour of grinding with them. 

Started at 12:18am CST, finished at 1:18am CST

ineseno road 14 $297
Procopio Drive 5 $505
Didion Drive 2 $256
Jamestown Street 30 / Apt11 $256
Steele Way 1 $229
Jamestown Steet 26 / Apt5 $256
Imagination Court 2 / Apt1 $207
Didion Drive 6 $290
I forgot this address but its next to the gopostal place $251
Spanish Avenue 5 / Apt2 $248
Jamestown Street 28 / Apt11 $326
DEL PERRO BEACH $297
Barrio $298
Forum Drive 10 / Apt1 $314
East Mirror Drive 9 $297
Mad Wayne Thunder Drive 6 $218
Alta Street 3 / Apt5 $259
Vespucci Boulevard 4 / Apt 2 $164
Forum Drive 2 / Apt21 $217

Total $5185

Repair cost $600
Fuel Cost $140

**Total Profit for 1 hour: $4445** (tipped $400 for the repair cause they opened up for me specifically, so actual profit was $4045

I can make that from 1 truck of hunting with a 500 pound trunk and a hunting rifle. This is supposed to be my job, so I guess I'm not understanding why I would go stand at the counter to maybe sell a meal or two for $130 profit each, or even go do deliveries when i can go do my "daily activities" (hunting, mining, z pills) for a few hours and make $60+

**Comment by vol5** [comment] 2023-02-24 08:20
This was a lot packed into one... But the main sentiment here is sound.

1. **I agree 100% that Z-pills should have food removed completely.** It seems to have been killing food biz RP for some time now. As a grinder I love being self sufficient and not having to pay for food. But it is a bit fucked that after doing zpills I have all the food I could need for the day. If food is removed completely from Z-Pills, the price you get per loot will be rebalanced as a lower amount down from $100-$200 to somewhere around $50-$100 because when you don't get an item you get an rng roll on cash.

2. There has been heavy focus on giving non whitelist jobs love. In terms of them being a heavy portion of the economy. And as @scufflord displayed the numbers with local deliveries. They are just not worth doing at all. 

Option A: it could be setup just like hunting, mining, and z-pills. There is a daily cap. Cap how many people can do and then buff the fuck out of the price per run. Eg. price range 600-800 per run with a cap of 15 runs each day. I know that you did not like the cap idea at first Laura but it does seem like a good option when compared to unlimited.

Option B: Base price increase with a cooldown after each run displaying a message "Seems like there are no orders right now. Go serve someone at the counter..". This forces players to stand around to wait. 

3. I do feel that crafting of the food should warrant a unique buff for the food on its own or "special effects". I've always been a fan driving player behavior due to the food holding a unique mechanic. eg. Lemonade (Sprint Faster). A cool new idea could be eg. Ice Cream (prevent stress for 60 seconds). Just an idea. New unique gameplay mechanics are dope.

The other points I'm not very opinionated on. But the main takeaway for me is z-pills food has now killed both of the other food joints and partially when this was not an issue, people still did not want to show up and RP with these spots. So I feel that more cash given back to the whitelisted jobs would be good to provide incentive. All because its funneling player traffic and creating more RP scenarios.

**Comment by scufflord** [comment] 2023-02-24 08:27
I would say a cap on the local deliveries even doesn't make sense, as it's part of my job. I'm typically around late night hours, 12am-4am, and there's no point in me standing at the counter for nobody to come by. But if people swing by while I'm doing runs, or tweet out, I immediately go back to the store to help them. Putting a cap on it puts a limit on how much I'm able to do my job, and a cap even at 15 runs assuming an $800 price per run still hits at $12k, a sum far below that of the other non-job dailies that we hear time and time again ARE NOT supposed to be the main source of income. 

In my opinion, buff the jobs, nerf the dailies. Get people back to working and roleplaying for their money instead of zombie survival simulator/minecraft simulator.

**Comment by navonody1** [comment] 2023-02-24 09:26
From the suggestions I'm seeing, the only thing that would drive people to food businesses is a list of items that have special effects like Vol5 suggested. Let's be honest, I could spend $0 and 5 minutes of my time and never go hungry or thirsty just by digging thru the trash. If you take food out of dumpsters; I can buy from fruit stands. Take away fruit stands; I go to convenient stores. Either way, there's no difference between the food at businesses and the other places I listed to get food. What's drawing people in to spend their money there?

Also from an RP standpoint, how is a legal citizen, not in the crime world, supposed to feel when walking into these food places where the employees constantly have colors showing and hang out in the parking lot with guns out talking about the person they just killed or the bank they just hit? It's intimidating to a normal person, so why would they spend their money at a place they don't feel safe or welcome? 

To scuff's point about the dailies...I can work at PDM and stand there for 4+ hours and have ONE person come in that's new and buy the cheapest vehicle there on finance and make $200-400. So even then, that $4k/hr doing deliveries would be better than just collecting a paycheck staring at a showroom full of cars. Same thing with lawyers, or people working at bars, etc. Not every business has a way to consistently work and make money, so the money you make doing dailies helps offset that. Granted, you do make A LOT from dailies compared to other activities available.

**Comment by coalaura** [comment] 2023-02-24 12:45
Okay, so basically:

> Remove food from zombie pills

This has already been done. I replaced all burgers, etc with fruits in the zombie pills. (#2606)

> let us grill 4 patties at once

This has already been suggested #2647

> I suggest putting this back into at least the french fries

Green Wonderland was struggling A LOT since i had added stress relief to food, thats why i reduced and/or removed the effect from most foods, NOT ONLY from burgershot food. I wont be adding it back since it shouldn't have been in food in the first place

> Actual Burger shot food .. I have the icons/food for the real menu items

Could you describe this in a bit more detail? What do you mean with actual burgershot food?

> We need an actual LOCKER put into the employee break room for staff to store stuff.

Why? What is there that they need to store for their job???? Mechanics have lockers for materials, PD has lockers for their equipment, the tuner shop has lockers for NOS bottles and tuner chips, what does burgershot need lockers for??

> I would love to have a menu put in kind of like the brochure

How would this be done? How would you be able to change the menu?

> Please please please the invisible barrier above the counter

This would be a suggestion for the asset github

> change the pay out for deliveries, and have a cool down period in between deliveries so it doesnt get abused

Why? What difference would this make?

**Comment by spitslave** [comment] 2023-02-25 02:24
> Okay, so basically:
> 
> > Remove food from zombie pills
> 
> This has already been done. I replaced all burgers, etc with fruits in the zombie pills. (#2606)
> 
> > let us grill 4 patties at once
> 
> This has already been suggested #2647
> 
> > I suggest putting this back into at least the french fries
> 
> Green Wonderland was struggling A LOT since i had added stress relief to food, thats why i reduced and/or removed the effect from most foods, NOT ONLY from burgershot food. I wont be adding it back since it shouldn't have been in food in the first place
> 
> > Actual Burger shot food .. I have the icons/food for the real menu items
> 
> Could you describe this in a bit more detail? What do you mean with actual burgershot food?
> 
> > We need an actual LOCKER put into the employee break room for staff to store stuff.
> 
> Why? What is there that they need to store for their job???? Mechanics have lockers for materials, PD has lockers for their equipment, the tuner shop has lockers for NOS bottles and tuner chips, what does burgershot need lockers for??
> 
> > I would love to have a menu put in kind of like the brochure
> 
> How would this be done? How would you be able to change the menu?
> 
> > Please please please the invisible barrier above the counter
> 
> This would be a suggestion for the asset github
> 
> > change the pay out for deliveries, and have a cool down period in between deliveries so it doesnt get abused
> 
> Why? What difference would this make?

Hello Laura, just wnt to add that food from Arcade and other restaurants also reduce stress, it wasn't just removed from Burgershot, I realized that a lot of the food from arcade and bean machien relieve stress. 
Food from burgershot no longer does that, so i think all food places should be relieved of that. 


Actual burgershot food would be things that people see on the menu that's above the register, there is like mexican pizza, chicken tenders, ice cream / shakes that i feel like should be added. I think people who date on the server would really like for cute little deserts to be added and their RP would enhance.

**Comment by selliee** [comment] 2023-02-25 05:17
> Okay, so basically:
> 
> > Remove food from zombie pills
> 
> This has already been done. I replaced all burgers, etc with fruits in the zombie pills. (#2606)
> 
> > let us grill 4 patties at once
> 
> This has already been suggested #2647
> 
> > I suggest putting this back into at least the french fries
> 
> Green Wonderland was struggling A LOT since i had added stress relief to food, thats why i reduced and/or removed the effect from most foods, NOT ONLY from burgershot food. I wont be adding it back since it shouldn't have been in food in the first place
> 
> > Actual Burger shot food .. I have the icons/food for the real menu items
> 
> Could you describe this in a bit more detail? What do you mean with actual burgershot food?
> 
> > We need an actual LOCKER put into the employee break room for staff to store stuff.
> 
> Why? What is there that they need to store for their job???? Mechanics have lockers for materials, PD has lockers for their equipment, the tuner shop has lockers for NOS bottles and tuner chips, what does burgershot need lockers for??
> 
> > I would love to have a menu put in kind of like the brochure
> 
> How would this be done? How would you be able to change the menu?
> 
> > Please please please the invisible barrier above the counter
> 
> This would be a suggestion for the asset github
> 
> > change the pay out for deliveries, and have a cool down period in between deliveries so it doesnt get abused
> 
> Why? What difference would this make?

For the Z pills- I just think all food items should be removed including fruit- the feedback from people are that they get an abundance of it that they dont need to go buy food for "days"

For something fun to be added to make the food at the establishment more desirable- what if a cool effect is put into place such as "luck" to make it so theres a chance to "not blow up in mining" or "gems sell for more" or something along those lines, something that will make people want to come buy food since stress relief is a no go.

Lockers- Bean Machine and the arcade too, have lockers. Lockers I believe are necessary because when we do have large orders the food itself until bagged, weighs a lot! Also- with larger orders for PD who usually order 20+ meals especially during trainings, we really need space in our pockets to hold that food. I find a lot of stuff on the floor in the kitchen area from people who place their belongings and sometimes they even forget it and it gets stolen from a civ or another employee. Sure, we can put stuff in our cars but it would just be nice to have a safe place to place stuff in the locker room.

Menu that opens like a brochure- I dont see a need to change the menu, it would be a generic menu [ive attached a picture] that would just remain the same.

For deliveries- Scufflord touched really well on this, and to be honest I feel like sure its an iffy thing.. making the deliveries pay more but in my time working/owning burger shot, the deliveries are what a lot of  the income is for the workers and is something that attracts people to want to work. If we want to talk about how people might grind them, i mean you can look at any other job - life invader jobs.. mining, hunting, etc. Can all be "grinded"  and make it so people dont need to actually show up to any job. So, as weird as it is for me to say it, all together having the deliveries pay more, I firmly believe will make people want to actually work at burger shot- making management RP a lot more enticing. 

As for the "actual burger shot menu items", The menu inside of burger shot.. advertises for things [ive attached a picture as well] and i think it would be so cool to have these actual items be able to be served to better the RP 
![Untitled design (1)](https://user-images.githubusercontent.com/90532434/221339794-1dde02e5-a857-497d-ad1c-8cf469e0df36.png)
![image](https://user-images.githubusercontent.com/90532434/221339798-79cf41a9-2186-4777-a160-9b10efc39ace.png)
![image](https://user-images.githubusercontent.com/90532434/221339802-ddcc9ca1-9378-451e-9a99-14f78b053c10.png)

**Comment by coalaura** [comment] 2023-02-25 11:59
@spitslave

> Hello Laura, just wnt to add that food from Arcade and other restaurants also reduce stress, it wasn't just removed from Burgershot, I realized that a lot of the food from arcade and bean machien relieve stress.
Food from burgershot no longer does that, so i think all food places should be relieved of that.

The only food from the arcade that removes stress was the pizza slice which removed 2% of your stress which is barely anything. Bean machine food still removes some level of stress but was greatly reduced, their food removes stress since all its other effects are very low so i left a little bit to compensate that.

---

@selliee 

> For something fun to be added to make the food at the establishment more desirable

I am not a big fan of adding a luck effect or something similar. Burgershot food is the most powerful food in the entire city, it fills up your hunger waaay more than anything else you can get.

> Menu that opens like a brochure- I dont see a need to change the menu, it would be a generic menu [ive attached a picture] that would just remain the same.

If it doesn't change, a nicer idea could be to replace the ads above the counter with some new images depicting said menu?

> For deliveries- Scufflord touched really well on this, and to be honest I feel like sure its an iffy thing.. making the deliveries pay more but in my time working/owning burger shot, the deliveries are what a lot of the income is for the workers and is something that attracts people to want to work. If we want to talk about how people might grind them, i mean you can look at any other job

I'm getting complaints from other subdivisions that people are ONLY doing deliveries and not actually working the job, so buffing them seems a bit iffy to me

> As for the "actual burger shot menu items", The menu inside of burger shot.. advertises for things [ive attached a picture as well] and i think it would be so cool to have these actual items be able to be served to better the RP

I fail to see how changing the icon of certain items would increase RP. Adding more food items that just end up doing the same idk man i'm not that big of a fan of that

**Comment by coalaura** [comment] 2023-02-25 12:01
@selliee In addition to what i mentioned with replacing these ads ![ads](https://i.shrt.day/hoPaXIzo41.png) if you wanna split up the menu into 4 images that have somewhat the format of those ads above the counter, i'll happily replace them right away as it would be rather trivial to do so and imo would be a lot nicer than brochures. (Also a lot easier to quickly get done)

**Comment by microwavablepizza** [comment] 2023-03-01 13:51
> @spitslave
> 
> > Hello Laura, just wnt to add that food from Arcade and other restaurants also reduce stress, it wasn't just removed from Burgershot, I realized that a lot of the food from arcade and bean machien relieve stress.
> > Food from burgershot no longer does that, so i think all food places should be relieved of that.
> 
> The only food from the arcade that removes stress was the pizza slice which removed 2% of your stress which is barely anything. Bean machine food still removes some level of stress but was greatly reduced, their food removes stress since all its other effects are very low so i left a little bit to compensate that.
> 
> @selliee
> 
> > For something fun to be added to make the food at the establishment more desirable
> 
> I am not a big fan of adding a luck effect or something similar. Burgershot food is the most powerful food in the entire city, it fills up your hunger waaay more than anything else you can get.
> 
> > Menu that opens like a brochure- I dont see a need to change the menu, it would be a generic menu [ive attached a picture] that would just remain the same.
> 
> If it doesn't change, a nicer idea could be to replace the ads above the counter with some new images depicting said menu?
> 
> > For deliveries- Scufflord touched really well on this, and to be honest I feel like sure its an iffy thing.. making the deliveries pay more but in my time working/owning burger shot, the deliveries are what a lot of the income is for the workers and is something that attracts people to want to work. If we want to talk about how people might grind them, i mean you can look at any other job
> 
> I'm getting complaints from other subdivisions that people are ONLY doing deliveries and not actually working the job, so buffing them seems a bit iffy to me
> 
> > As for the "actual burger shot menu items", The menu inside of burger shot.. advertises for things [ive attached a picture as well] and i think it would be so cool to have these actual items be able to be served to better the RP
> 
> I fail to see how changing the icon of certain items would increase RP. Adding more food items that just end up doing the same idk man i'm not that big of a fan of that

I can confirm that adding more food options to the menu will bring RP. It's been what, years now with Burgershot only having burgers and fries? It would be more inticing if I could order more stuff such as a goat wrap or milk shake if anything. At the end of the day, the reason Burgershot falls off is because there's nothing to make it special, e.g it only just has burgers, fries, drinks vs the menu advertising such. After working at Burgershot a long time, we would have new players come into the store and look at the menu that's depicted above and weigh their choices and have fun actually trying to figure out what they want to order meanwhile I'm waiting to be like 'Sorry dude, this Burgershot only sells burgers, fries, and an avocado smoothie' Like so basic, y'know. It gets old, and after some time, it doesn't hurt to try a little bit of change. I feel like the people who at least take their time of the day to play Legacy deserves that much. Whether it's something that can be implimented easily or something much more complicated, I believe everyone at least deserves the effort.

**Comment by microwavablepizza** [comment] 2023-03-01 14:05
> Okay, so basically:
> 
> > Remove food from zombie pills
> 
> This has already been done. I replaced all burgers, etc with fruits in the zombie pills. (#2606)
> 
> > let us grill 4 patties at once
> 
> This has already been suggested #2647
> 
> > I suggest putting this back into at least the french fries
> 
> Green Wonderland was struggling A LOT since i had added stress relief to food, thats why i reduced and/or removed the effect from most foods, NOT ONLY from burgershot food. I wont be adding it back since it shouldn't have been in food in the first place
> 
> > Actual Burger shot food .. I have the icons/food for the real menu items
> 
> Could you describe this in a bit more detail? What do you mean with actual burgershot food?
> 
> > We need an actual LOCKER put into the employee break room for staff to store stuff.
> 
> Why? What is there that they need to store for their job???? Mechanics have lockers for materials, PD has lockers for their equipment, the tuner shop has lockers for NOS bottles and tuner chips, what does burgershot need lockers for??
> 
> > I would love to have a menu put in kind of like the brochure
> 
> How would this be done? How would you be able to change the menu?
> 
> > Please please please the invisible barrier above the counter
> 
> This would be a suggestion for the asset github
> 
> > change the pay out for deliveries, and have a cool down period in between deliveries so it doesnt get abused
> 
> Why? What difference would this make?

Removing all the food from Z pills will be a good thing to go for, even fruit stacks up and still counts a lot.
If Arcade is allowed to have what, their 2% in reducing stress, Burgershot should at least have something similar to that 2%. I get that you guys want to encourage Green Wonderland, but at least make it clear across the field. If the Arcade is going to have food, at least make it fair across the board since they are the ones getting more traffic for their Z pills. It's not fair to other food establishments if they are prioritized when it comes to both food and the Zpills(which still include food). 

I also +1 for Burgershot needing lockers for workers. I don't know if you have ever been in burgershot before, but if you come inside with a full inventory, you end up having to put stuff in the corners in the back. The material to cook the burgers and the smoothies itself are heavy, just like mechanic material is heavy also. Same concept. If there was a locker in the lockroom to just store those simple things that people have when they come in to work, that would be great. It's a simple request for when the workers get big orders. Its nothing big, nothing extreme which will affect other people outside of the workers.

**Comment by kaycorriher** [comment] 2023-03-10 03:18
Personally, I think a locker could be good as I have had my personal items in my pocket and only be able to cook 4 burgers because my personal items were too heavy for me to cook all the patties for the order. I had to throw my stuff in a pile on the floor and its just an eye sour.

**Comment by coalaura** [comment] 2023-03-14 14:12
locker was added btw

**Closed** 2023-11-09 12:11 UTC
Labels: suggestion
