### ISSUE TITLE
[illegal/cocaine] Coke Plane Despawning / Coke Brick Not Appearing

### ISSUE THREAD

**Issue by sleighwhite** [InZidiuZ/op-framework-issue-tracker#1884] opened 2021-06-18 16:11 UTC
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Player Identification:**
What is your steam profile?

sleighwhite

**Summary:**
Write a short summary of what you are experiencing.

The cocaine will occasionally not spawn properly after paying to start the mission. It will appear briefly and then automatically despawn causing the player to fail the mission and lose $1,000. It appears to be happening at different frequencies for different players. 

Additionally - sometimes the plane will spawn and the player will be able to attempt the mission; however, when they get to the ocean to pick up the package, it's not there. 

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.

Pay to start cocaine run mission
Plane will spawn/despawn

**Expected Results:**
What are the expected results?

Expect the plane to spawn and there to be a package in the ocean

**Actual Results:**
What are the actual results?

Plane may despawn automatically or there may be no package in the ocean.

## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.

**Server:**
What server/community did this issue occur in?

OPFW - UK/NA

**Notes:**
For anything else noteworthy.

**Comment by InZidiuZ** [comment] 2021-06-21 10:20
Not able to reproduce at this time. I made some adjustments, but this system is deprecated so I'm leaving this as a wontfix.

**Closed by InZidiuZ** 2021-06-21 10:20 UTC
Labels: bug, illegal/cocaine
