### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by tbone0tbone** [InZidiuZ/op-framework-issue-tracker#2044] opened 2021-10-12 21:15 UTC
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Summary:**
Write a summary of what your suggestion is about.
I believe a /frisk option should be added for police to use and also for the security role 
**Reason:**
Why would your suggestion be a good change to the framework?
The reason this would be a good change is that it enhances rp instead of /search and straight up seeing what someone has in their inventory I think frisking would allow people to play out a story better. The reason I think it should be added for the security role because they should be able to find out if someone is bringing a gun into their place of work without looking into the persons pockets

**Comment by twooot** [comment] 2021-10-13 22:12
How would it work? Would it tell you if the person has a gun or also small weapons like knives?

**Comment by twooot** [comment] 2021-10-20 22:15
Closed due to being a duplicate of the above-mentioned suggestion. I'll look into this and come up with something

**Closed as completed by twooot** 2021-10-20 22:15 UTC
Labels: suggestion
