### ISSUE TITLE
[game/furniture] Bug report Black Infinite loading screen trying to enter house

### ISSUE THREAD

**Issue by seekertransformer** [InZidiuZ/op-framework-issue-tracker#1773] opened 2021-04-23 17:22 UTC
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository? Yes

**Player Identification:**
What is your steam profile? 
IndigoVixen01
Steam ID: 76561199150284590 

**Summary:**
Write a short summary of what you are experiencing.
I live at the low end apt Las Lagunas blvd 5/ apt 1 (thats exactly how its written im not sure about "E") this morning loaded in w black screen o death. I do believe if the issue is furniture it would be that I have an arcade in there. I had it there before the update where you could actually use it and since the update ive been able to play it in my apartment but that issue also came up after the fact! 

**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
I either load in and try to spawn at my apartment or I am able to enter at some point and then others not while in city already.

**Expected Results:**
What are the expected results?
To be able to enter and have guests enter my apartment. I would like to physically keep the arcade furniture if possible but if its that i cant play it anymore that is okay. 

**Actual Results:**
What are the actual results? Black screen that never loads my apartment interior I end up having to disconnect and restart

## Additional Information

**Screenshots:**
If suitable, include some screenshots.

**Game Resolution:**
What is your game's resolution? 1920x1080

**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.

**Server:**
What server/community did this issue occur in? Legacy RP NA/EU

**Notes:**
For anything else noteworthy.

**Comment by seekertransformer** [comment] 2021-04-23 17:23
![Screenshot (18)](https://user-images.githubusercontent.com/82508942/115907540-e05b0380-a41d-11eb-9208-c80f4235813e.png)
![Screenshot (19)](https://user-images.githubusercontent.com/82508942/115907543-e0f39a00-a41d-11eb-957e-f21c6d3c73ac.png)

**Comment by seekertransformer** [comment] 2021-04-27 21:44
Hello this is still an issue for me that seems to be worse, i could at least get in upon loading but today I decided I want to just get a new apartment and unload all my inventory from that one... but i cant even get in on loading anymore... I just hard napped like 5 times trying to get inside. I just want to move out and take my stuff out at this point...

**Comment by InZidiuZ** [comment] 2021-04-29 09:25
I just looked into your apartment with your furniture on a local server, but I was not able to reproduce. It might have to do with that the assets on the prod servers are outdated & is missing some fixes. I'm not able to merge assets yet as I'm waiting for someone else to complete some work.

**Comment by seekertransformer** [comment] 2021-04-29 19:00
This being closed, and still having the issue with my apartment today do I open a new issue ticket? I am still having the exact same issues same apartment. Just tried getting in and again infinite black screen.

**Comment by InZidiuZ** [comment] 2021-04-30 09:14
This issue is not closed. The latest assets has still not been merged.

**Comment by seekertransformer** [comment] 2021-05-01 00:46
Okay my bad! I just misunderstood. Thank you sm for doin the great wrks! x

**Comment by InZidiuZ** [comment] 2021-05-17 10:59
Is this still a problem?

**Comment by InZidiuZ** [comment] 2021-05-18 05:52
If this is still a problem, please create a new issue.

**Closed by InZidiuZ** 2021-05-18 05:52 UTC
Labels: bug, feedback/discussion needed, game/furniture
