### ISSUE TITLE
we cannot hear our friends while car is moving

### ISSUE THREAD

**Issue by ombelani** [InZidiuZ/op-framework-issue-tracker#815] opened 2020-02-18 02:40 UTC
**Reporter:**
John D#1461

**Summary:**
while i was driving a car with my friend siting inside i cannot hear him while driving fast than 60 km/hr. And this is happening with everyone in game everyday even after reporting in discord server.

**Expected Results:**
like before we should get to listen them 

**Game Resolution:**
1920*1080

**Server:**
India

**Comment by iGreatWhite** [comment] 2020-02-18 07:14
Which is caused by onesync btw. Not much InZidiuZ can do right now about it.

**Comment by ombelani** [comment] 2020-02-18 07:29
I had known that but my suggestion is to make normal servers

**Comment by iGreatWhite** [comment] 2020-02-18 07:30
He probably won’t revert the servers back. He will probably just add Tokovoip possibly to fix the voice issues but that is all up to him just letting you know the cause of what the issue was.

**Comment by ombelani** [comment] 2020-02-18 07:33
Sir I can understand that but there are even many glitches included with it
like car gets dissaepare, facial hair gets dissaepare next time I open game
also mask

**Comment by InZidiuZ** [comment] 2020-02-18 07:41
Hey,

This is unrelated to the framework, so closing.

**InZidiuZ**
*OP-FW Developer*

**Closed by InZidiuZ** 2020-02-18 07:41 UTC
Labels: bug
