### ISSUE TITLE
Tuner Shop - Legacy Racing Crew Mechanics / Whitelisted Job. (Name change available)

### ISSUE THREAD

**Issue by ZurxeyH** [InZidiuZ/op-framework-issue-tracker#559] opened 2019-10-22 03:35 UTC
**Name:**
Who is suggesting this? Please include discord name.
Zurxey#2607 - https://steamcommunity.com/id/Zurxey

**Summary:**
Write a short summary of what your suggestion is about.

First steps would be remodeling Bennys to allow us an inner city area for the crew itself, and RP. (LSC, mechanic shop, car wash, etc) 

Benny's Idea Layout: 

Area for the shop(back right corner)
- http://prntscr.com/px4b7p 

Review Stand(review vehicle repairs)
- http://prntscr.com/px4ayc

Working Station(workbench)
- http://prntscr.com/px4agg

Purchasing Area(materials)
- http://prntscr.com/px4amo

Los Santos Customs(yenno)
- http://prntscr.com/px4bj3

LRC's Tunershop area(illegal car modifications, plate sales, whitelists to it, tunerchips, maybe import cars?) 
- http://prntscr.com/px4byg

*Hopefully we could get the garage door to open :)* 

A new illegal/legal modification to vehicles.
- My crew, Legacy Racing Crew is dedicated to providing the best of best races, mechanics, and tunes in the business.
- We are wondering if it would be possible to get a new interior put in at a certain location for a large mechanic shop, kinda like the lost, or if we could get special operation access to Bennys, including a mechanic shop, and room.)
- At this shop we would have access to a Los Santos Customs, Car Wash, and of course the Mechanic shop. This would be our dedicated job, and we would spend most of our time there.
- I'm hoping to also have a new modification to vehicles, known as "Tuner parts.”
- These new vehicle addon parts would allow the vehicle to drive, handle, and provide a higher top speed, for a price of course. (Prices would be split between LRC TUNERS and State account)
- This would provide a whole new way of Roleplay, and allow my Crew and myself to grow, and do what we all love. Mechanic, and Racing. 
- This would basically be a NoPixel tuner shop, where we can repair, upgrade, and show vehicles. 
- I, Andrew Smith would be leading the shop, and overseeing it. Making sure the RP is up to standard, that we are functionally working, and providing the community with something new.

This has been an idea for a while, and I believe it would be an amazing addition to Legacy. I have had many community members tell me the same, and I am wishing to see what the other part of the community thinks.

New updates:
Allowing us to have a supply of Fake Plates, and Tuner Parts of course. 

 

**Reason:**
Why would your suggestion be a good addition to Legacy?
I believe this would be an amazing addition to Legacy as it will provide a new, interesting mechanic to vehicles, bring loads of new roleplay, provide a new business with an amazing privilege, and allow the community to understand, upgrade, and just overall bond over cars, whether it be off road, suvs, supers, or sports cars.
This is a COMMUNITY Suggestion.
Of course it will be ran like a new job, hopefully we will have whitelisted permissions, etc. But it will provide plenty of roleplay, and money to the "state" along with making community members happy :D

If you have any suggestions, comments, concerns, please reply below! 
Also +1 this if you think it'd be a great addition! I am so hyped, and so pumped to continue on with Legacy Racing Crew, and Legacy Roleplay as a whole.

**Comment by Aspratic** [comment] 2019-10-23 22:27
I have had good roleplay with their group and they have continued to embrace and run the street racing scene. I see this as a good fit for our community and think they are worthy of a tunershop. If they are given a whitelist to add illegal mods, the mods should be expensive to add-on and if police search the engine before impounding the car and see the illegal mods on it they get removed and you will have to re-buy the illegal upgrades.

**Comment by Cricketx818** [comment] 2019-10-23 23:33
So the problem is, If you guys get a "illegal mods shop" Its gotta be a job title and a "White listed job" I am not sure how it would make money or make any sense to open one up so it doesn't hurt the economy, It might have to be like you must mind your own materials to "craft" a turbo for u guys to be able to sell it, or something like that, Then that would make sense. I doubt its going to be Government funded for a "Bigger Turbo"  Pretty much work hard enough to craft the mod to customers would only make sense.

**Comment by Aspratic** [comment] 2019-10-24 00:59
I agree with Cricket, it shouldn't be government funded. You guys would have to spend big bucks up front, maybe 50k for the base price and then you guys have to craft the other half. Sell for maybe a 10k profit so like 65k sell. (other 5k would be materials and stuff to craft)

**Comment by ZurxeyH** [comment] 2019-10-24 19:08
> 
> 
> So the problem is, If you guys get a "illegal mods shop" Its gotta be a job title and a "White listed job" I am not sure how it would make money or make any sense to open one up so it doesn't hurt the economy, It might have to be like you must mind your own materials to "craft" a turbo for u guys to be able to sell it, or something like that, Then that would make sense. I doubt its going to be Government funded for a "Bigger Turbo" Pretty much work hard enough to craft the mod to customers would only make sense.

However it would work out is what i'm aiming for, I do agree with you on this, maybe we should take a much more legal idea, instead of trying to do things under the table.

**Comment by ZurxeyH** [comment] 2019-10-24 19:31
> 
> 
> I agree with Cricket, it shouldn't be government funded. You guys would have to spend big bucks up front, maybe 50k for the base price and then you guys have to craft the other half. Sell for maybe a 10k profit so like 65k sell. (other 5k would be materials and stuff to craft)

This could be a solution. :D

**Comment by ZurxeyH** [comment] 2019-11-14 22:54
bump, big updates.

**Comment by DaxterPancake** [comment] 2019-11-14 23:35
Personally I don't feel like you should be given Fake Plates and Tuner Parts/Chips for free. The Lost offer these modifications but spend time and money to obtain said items.

**Comment by TwoplePop** [comment] 2019-11-14 23:39
If we were given them for free, they would probably be non profit for us. if they are earned or payed for, the money would probably go to us.

**Comment by DaxterPancake** [comment] 2019-11-14 23:42
I like that way of looking at it, would that mean if they are given for free, you'd offer free tunes and what not? Coz if that's the case, sorry Lost, I know where I am goin'. :^)

**Comment by ZurxeyH** [comment] 2019-11-14 23:48
> 
> 
> I like that way of looking at it, would that mean if they are given for free, you'd offer free tunes and what not? Coz if that's the case, sorry Lost, I know where I am goin'. :^)

Lost is a massive business partner of ours, if we ever received this, and were actually profitable (we would have to buy them from ourselves of course, and also sell them, profit a bit, and PAY the government a lump sum) 
But if this were to happen, it wouldn't be about us getting them for free, or us making a shit ton of money off it. It's more or less for the roleplay, and the idea behind it. It's the main reason why I am going to be sticking around Legacy, in hopes this happens, as I personally feel it would majorly change LRP for the better future.

**Comment by InZidiuZ** [comment] 2020-02-13 21:14
Hey,

Will close this as it does not comply with the framework standards of FFA RP features. The only exclusive features should be actual game-implementations such as 'Vanilla Unicorn', 'The Lost MC', 'Tequi-la-la', etc.

If you'd like to rework this suggestion, feel free to create another issue.

**InZidiuZ**
*OP-FW Developer*

**Closed by InZidiuZ** 2020-02-13 21:14 UTC
Labels: new feature, suggestion
