### ISSUE TITLE
Bug report - Config doesn't work well

### ISSUE THREAD

**Issue by uolla** [InZidiuZ/op-framework-issue-tracker#3400] opened 2024-05-19 20:53 UTC
### Assurance

I have read the `README.md`

### Reporter

GambloTwitch

### Summary

Cluster 5 we have our own config, uploaded correctly as Ben said to me too.
But:
disable_kill_confirmation = false / doesn't seem to change anything in-game.
respawn_item_penalty = false / people lose items anyway.
enable_critical_hits = true / headshots don't kill

### Steps to Reproduce

We tried to headshot someone, we tried to respawn to check if items were lost, and we tried to kill someone trying to see if there's any kill confirmation thing... nothing.

### Expected Behavior

Should be the correct behaviour stated by the config file.

### Actual Results

Opposite results of what we set.

### Screenshots/Videos

https://i.imgur.com/LPDiGQk.mp4

### Player Data

https://i.imgur.com/YThAfsn.png

### Server

Italy (c5s1.op-framework.com)

**Comment by coalaura** [comment] 2024-05-19 21:54
`disable_kill_confirmation` is not a valid config, i've tested `respawn_item_penalty` and `enable_critical_hits` and they work for me, did you restart your server after changing the config and was your config change merged before you did?

Here is a the documentation containing all config parameters btw: https://docs.opfw.net/config

**Comment by uolla** [comment] 2024-05-19 21:56
Yes we did, and it says it's loaded properly too. But, as you can see from video, it's not going to oneshot.

**Comment by coalaura** [comment] 2024-05-19 21:58
The `enable_critical_hits` config option will just not disable critical hits. Critical hits are a part of GTA itself, so i'm not sure if they maybe changed something with it or so. I'll take a closer look.

**Comment by InZidiuZ** [comment] 2024-05-20 20:29
The critical hits config has been renamed to `disable_critical_hits` and when enabled, it will treat headshots as a body shot. Shooting someone with a pistol in the head:
- Disabled (default game behavior): https://inzidiuz.com/78PUnO.png
- Enabled (treats the headshot as a body shot): https://inzidiuz.com/HslodY.png

I've also made adjustments to `disable_kill_confirmation` to properly activate and deactivate on both true & false:
- Disabled config (default game behavior): https://inzidiuz.com/QZcr61.mp4
- Enabled config (does not show the effect): https://inzidiuz.com/xFfAy1.mp4

I've tested `respawn_item_penalty` and it was working as intended locally. I loaded your config as well and it was set to false and I was not losing items when respawning. If it happens again, please provide a clip with a timestamp of when it happened in DMs so it can be looked into further.

**Closed by InZidiuZ** 2024-05-20 20:29 UTC
Labels: bug
