### ISSUE TITLE
Bug report - Raspberry Issue

### ISSUE THREAD

**Issue by J33TGAMER** [InZidiuZ/op-framework-issue-tracker#2910] opened 2023-08-15 05:44 UTC
### Assurance

I have read the `README.md`

### Reporter

J33T#4060

### Summary

After Using Terminal Command Raspberry Is Not Opening . I Have Raspberry In My Inv Too..

### Steps to Reproduce

Keeping Raspberry In Inv... And Using /Terminal Command

### Expected Behavior

To Open Hacking Device

### Actual Results

Black Screen On Command / Terminal.. And It Does Not Load Completely 

### Screenshots/Videos

https://cdn.discordapp.com/attachments/731781103538536528/1139922428437463121/image.png

### Game Resolution

1920x1080

### Player Data

https://cdn.discordapp.com/attachments/741958310085001226/1140883607431417856/image.png

### Server

India (c8s1.op-framework.com)

**Comment by coalaura** [comment] 2023-08-15 23:31
I am unable to reproduce this ![hmm](https://i.shrt.day/fEmUxATu37.png)

**Comment by J33TGAMER** [comment] 2023-08-16 13:58
This Bug Is Happening With Very Few People In Server , You Can Check This Video : - https://drive.google.com/file/d/13AV-o3NR5DJhlJGe3I4WSh2k-eYUVYQQ/view?usp=sharing

**Comment by J33TGAMER** [comment] 2023-08-18 10:30
Any Help For This??

**Comment by J33TGAMER** [comment] 2023-08-22 13:04
Can u help me with this issue??

**Comment by J33TGAMER** [comment] 2023-08-28 18:11
@coalaura 
@InZidiuZ

**Comment by J33TGAMER** [comment] 2023-08-28 18:12
IG This Issue Is With New Players Like My Friend Also Did He Came 1-2 Week Ago He Also Cant Access it
And Whoever Joined In Starting They Can Do It

**Comment by coalaura** [comment] 2023-08-28 19:12
The issue will not be fixed faster the more you ping and ask, it will be fixed when one of us gets around to it and is actually able to reproduce it

**Comment by Sniperplays078** [comment] 2023-11-09 11:55
same error i am also getting while opening terminal

**Comment by Sayan4254E** [comment] 2023-11-09 17:53
> This Bug Is Happening With Very Few People In Server , You Can Check This Video : - https://drive.google.com/file/d/13AV-o3NR5DJhlJGe3I4WSh2k-eYUVYQQ/view?usp=sharing

Link is expired 🙂

**Comment by coalaura** [comment] 2023-11-16 14:51
With the recent update, is this still an issue?

**Comment by coalaura** [comment] 2023-11-19 23:14
reopen if its still an issue

**Closed** 2023-11-19 23:14 UTC
Labels: bug
