### ISSUE TITLE
Suggestion - Stockade

### ISSUE THREAD

**Issue by sakar5157** [InZidiuZ/op-framework-issue-tracker#2980] opened 2023-10-12 11:18 UTC
### Assurance

I have read the `README.md`

### Summary

Would be better if we can still see the stockade blip while holding shift.
And after the back door is triggered, the truck should share its live location on the blips.

### Reason

Its difficult to respond from PD side when the stockade is inside tunnels and moving the stockade to diffrent location after using lockpick makes it harder.

**Comment by coalaura** [comment] 2023-10-13 13:09
duplicate of #2793

**Closed by coalaura** 2023-10-13 13:09 UTC
Labels: suggestion
