### ISSUE TITLE
Suggestion: Cooking and Farming

### ISSUE THREAD

**Issue by SsieylumM** [InZidiuZ/op-framework-issue-tracker#2258] opened 2022-04-10 23:58 UTC
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes

**Summary:**
A great addition would be the Ability to Cook and Farm. Farming and Cooking would coincide with one another as the farming aspect may include the ability to buy out farms around the map and grow various vegetables and fruits to then either sell to a restaurant or use in your own restaurant to then cook meals with meat (maybe even add different varieties of meat) and then sell in said restaurant. 

The food cooked in restaurant will be subject to the pricing of the restaurant but will most likely end up being more expensive than for eg. BrugerShot and Bean Machine however give better saturation benefits or other stat boosts. These restaurants will be perfect for; social gatherings, dates, events and much more.

The Ability to cook could also be available to those who own a house but the stat and saturation boosts would not be as efficient and gaining as food from a restaurants would be and the process can also be made harder but less expensive to balance everything out.

**_LESS REALISTIC IDEA_**
Another cool addition for this would be the ability to develop your characters cooking skill by cooking more and more food and certain foods require a certain skill level to cook and the better your cooking skill the better the stats you gain from the food is and maybe even your skill determines the length it takes for one to make a meal. I also think that not all recipes for meals you can cook should be made public this may encourage the players to publish cook books to help others improve their cooking skill and share recipes they have discovered. However I don't know if this will be received ass well as the prior ideas as this "skill" system isn't implemented anywhere else in the city

**Reason:**
Why would your suggestion be a good change to the framework?

The ability to cook and farm would add multiple job opportunities allowing for other sources of income such as selling products from the farms and opening up family owned restaurants or even grocery stores where people can buy products from farms (jobs within the restaurants like a chef would have to have varying pays depending on the chefs cooking skill). This will also add an extra level of RP as currently the only access to food we have is Either take away style food or snacks from the store and there is no real immersive experience with cooking. Also just the ability to cook or farm would be a really cool aspect as it is something fresh and new for RP'er's to experience.

I understand that this will be a long a tedious task to complete but I hope you take it into consideration as I really think it would help develop the server  exponentially and I know everything in here will definitely not be implemented but I hope you take some sort of inspiration or develop a concept to implement off this suggestion.

**Comment by CloudTheWolf** [comment] 2022-04-11 07:56
We already have a way to cook meat (from hunting), and Burger Shot have to actually make then food so the foundation is there.
I would like to see different meats that could be cooked, as well as the ability to cook (craft) different things based on ingredients. Eg Sushi (When fishing is eventually added), Steak and Chips, Soup, and other things.

Some ideas for ingredients could be:

Chicken (Could craft into different things)
Pork (Could be crafted into Sausages) 
Beef (Could be crafted into Burgers)
Rabbit (Another thing from Hunting) 
Fish (When fishing is added)

Lettuce 
Cabbage
Potato
Sweet Potato
Rutabaga (Aka Swede)
Mushrooms (Not the illegal kind xD)

This would also allow for more RP for bars such as the Irish Pub as they could hire a cook.

**Comment by coalaura** [comment] 2023-03-12 18:42
Closing as duplicate of #2258

**Closed by coalaura** 2023-03-12 18:42 UTC
Labels: suggestion, essay
