### ISSUE TITLE
[game/furniture] Bug report Black Infinite loading screen trying to enter houseBug report

### ISSUE THREAD

**Issue by seekertransformer** [InZidiuZ/op-framework-issue-tracker#1792] opened 2021-04-29 19:04 UTC
Assurance:
Have you read through the rules from the README.md file in the root folder of this GitHub repository? Yes

Player Identification:
What is your steam profile?
IndigoVixen01
Steam ID: 76561199150284590

Summary:
Write a short summary of what you are experiencing.
I live at the low end apt Las Lagunas blvd 5/ apt 1 (thats exactly how its written im not sure about "E") this morning loaded in w black screen o death. I do believe if the issue is furniture it would be that I have an arcade in there. I had it there before the update where you could actually use it and since the update ive been able to play it in my apartment but that issue also came up after the fact!

Steps to Reproduce:
Include what steps that are needed in order to reproduce this issue.
When I first load in I choose that apartment and attempt to enter sometimes works most times it fails. it could work like one out of 10 times i try. The other way is when I already loaded in from another location and try to enter it, doesnt ever load up. 

Expected Results:
What are the expected results?
To be able to enter and have guests enter my apartment. I would like to physically keep the arcade furniture if possible but if its that i cant play it anymore that is okay. If possible at this point I just want to retrieve my inventory and get a different apartment.

Actual Results:
What are the actual results? Black screen that never loads my apartment interior I end up having to disconnect and restart everytime 
Additional Information

Screenshots:
If suitable, include some screenshots.

Game Resolution:
What is your game's resolution? 1920x1080

Player Data:
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.

Server:
What server/community did this issue occur in? Legacy RP NA/EU

Notes:
For anything else noteworthy.

**Comment by InZidiuZ** [comment] 2021-05-05 07:43
Duplicate of #1773.

**Closed by InZidiuZ** 2021-05-05 07:43 UTC
Labels: bug
