### ISSUE TITLE
Emote binds no longer working

### ISSUE THREAD

**Issue by novapurple** [InZidiuZ/op-framework-issue-tracker#1584] opened 2020-12-19 16:30 UTC
**Assurance:**
Have you read through the rules from the `README.md` file in the root folder of this GitHub repository?
Yes
**Player Identification:**
What is your steam profile?
https://steamcommunity.com/id/NovaPurple/
**Summary:**
Write a short summary of what you are experiencing.
no longer able to bind emotes with /emote bind
**Steps to Reproduce:**
Include what steps that are needed in order to reproduce this issue.
/emotebind num7 crossarms5 \ or any other emotes 
see if it works(lets you use the shortcut for it)
**Expected Results:**
What are the expected results?
/emotebind num7 crossarms5 \ or any other emotes and will bind them and let you use them
**Actual Results:**
What are the actual results?
does not bind the emotes to it but lets you type it out
## Additional Information

**Screenshots:**
If suitable, include some screenshots.
https://user-images.githubusercontent.com/58092783/102694161-496f0800-41ed-11eb-8352-6e1725d32783.png
https://user-images.githubusercontent.com/58092783/102694181-702d3e80-41ed-11eb-8ca4-5aa7bee0138e.png

**Game Resolution:**
What is your game's resolution?
1920x1080
**Player Data:**
Write '/info' whilst in-game and provide a screenshot of the information you are prompted.
https://user-images.githubusercontent.com/58092783/102694193-820ee180-41ed-11eb-9b5c-79c06176ff15.png

**Server:**
What server/community did this issue occur in?
International 
**Notes:**
For anything else noteworthy.

**Comment by mxttx** [comment] 2020-12-19 21:33
This is intermittent - I remember having this issue back in October, but I can't replicate this right now.

**Comment by InZidiuZ** [comment] 2020-12-20 00:03
This is an external & deprecated system, and I'm not able to reproduce it locally, so will close this and leave it as a wontfix

**Closed by InZidiuZ** 2020-12-20 00:03 UTC
Labels: bug
