### ISSUE TITLE
[Phone Suggestion] Wrong time on phone inside house.

### ISSUE THREAD

**Issue by adityaef** [InZidiuZ/op-framework-issue-tracker#618] opened 2019-11-04 13:53 UTC
# Legacy Phone Suggestion
**Name:**
harshef#4473

**Summary:**
The phone clock always shows 22:00 inside the apartment/house.

**Reason:**
We need to go outside the house to check the correct time. During house robberies, we can't see how much time is left until the morning.

**Comment by Anderzenn** [comment] 2019-11-04 15:43
Hi :)
This is a bug with GC Phone and not our own phone.

This will not be a problem with our future phone, so I am closing this issue.

**Anderzenn**
*OP-FW UI Developer*

**Closed by Anderzenn** 2019-11-04 15:43 UTC
Labels: phone

**Comment by HridayHS** [comment] 2019-11-04 16:26
This is actually not a bug rather intentional to stop "weird lightning effects".
I remember InZiduZ telling that this is intentional.

**Comment by Anderzenn** [comment] 2019-11-04 16:41
Still a bug with how GC Phone tells you what time it is

**Comment by Anderzenn** [comment] 2019-12-27 23:52
Scratch what I said earlier, this is done intentionally.
