### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by kaetarian** [InZidiuZ/op-framework-issue-tracker#1837] opened 2021-05-24 21:41 UTC
Steam: https://steamcommunity.com/profiles/76561197993789770/

I have a Michaels Mansion on Steele Way 5 and every time we try to decorate it our heads pop when we try to enter. Once we get back into the city it's fine until we drive away from it and come back. We have gone through the process of changing out the items we are putting in there and reverted it back several different times.

**Comment by DaxterPancake** [comment] 2021-05-24 21:46
Closing due to not following the template.

Go [here](https://github.com/InZidiuZ/op-framework-issue-tracker/issues/new/choose).
Select BUG REPORT. 
You will then be brought to a page that looks like this:
![image](https://user-images.githubusercontent.com/50828532/119411002-0b8e8680-bd2d-11eb-8539-dcec830b43b4.png)
In section **1** add a basic title for your issue (3-10 words).
In section **2** this is where you fill in as many sections as you can. Please provide as much information as you can such as screenshots and photos. This helps us figure out what the issue is. It is important to try and fill out as much as you can.

Cheers,
Daxter.
Project Manager.

**Closed by DaxterPancake** 2021-05-24 21:46 UTC
Labels: bug
