### ISSUE TITLE
Bank Robbery System Not Working

### ISSUE THREAD

**Issue by DooZolz** [InZidiuZ/op-framework-issue-tracker#295] opened 2019-07-27 16:22 UTC
**Reporter:**
DooZolz#4014 https://steamcommunity.com/profiles/76561198185121513/home

**Summary:**
So basically I've been kidnapped around 2-3x today and they have all used me as a hostage in a bank robbery. I noticed that none of the bank robbery's were actually successful. The most recent one was this guy who kidnapped used 4 thermite on the vault and it didn't work for him. The cops even did a /closebank command and it still didn't work. I don't really know how this robbery system works but hopefully you can check out the issue.

**Steps to Reproduce:**
Fix the issues lol.

**Expected Results:**
When you rob a bank you actually get the money and don't 

**Actual Results:**
What are the actual results?

## Additional Information

**Screenshots:**
If suitable, include some screenshots. You also *have* to include screenshots of your F8 console.

**Game Resolution:**
What is your game's resolution?

**Player Data:**
Write /info whilst ingame and provide the information you're given.

**Notes:**
For anything else noteworthy.

**Comment by DooZolz** [comment] 2019-07-27 16:28
My computer legit crashed half way I was writing this so if you want just take it down.

**Comment by InZidiuZ** [comment] 2019-07-27 18:38
Incomplete report, no repro, don't really understand what you mean the issue is, closing.

**Closed by InZidiuZ** 2019-07-27 18:38 UTC
Labels: bug
