### ISSUE TITLE
[game/inventory] Inventory

### ISSUE THREAD

**Issue by maguhd** [InZidiuZ/op-framework-issue-tracker#915] opened 2020-04-05 08:26 UTC
**Reporter:**
MaguHD#8534
https://steamcommunity.com/id/maguhd/

**Summary:**
Property inventory does not update when I try to take weed out. This happens with weed only for me. Some people experience this with all their items. If I store the weed inside the box, it updates. I only cannot take it out.

**Steps to Reproduce:**
https://streamable.com/0722qh

## Additional Information

**Screenshots:**
https://prnt.sc/rtc0ir

**Game Resolution:**
1920*1080

**Player Data:**
https://prnt.sc/rtbzut

**Server:**
Main

**Comment by maguhd** [comment] 2020-04-05 09:06
https://streamable.com/z29yii

**Comment by MPar22** [comment] 2020-04-05 15:41
I am having the same issue. It seems as though weed you harvest from plants you grow inside of your property is bugged. For some reason the whole storage crate is scuffed and doesn’t allow you to take any items out.

**Comment by InZidiuZ** [comment] 2020-04-05 17:47
Thank you for the detailed video!

I saw this happen to someone else too, but once I added debugging to the inventory figure out the cause, it fixed itself... 😕

Did you try restarting your game, and if so, was it the same? Do you also know if it is still an issue after the restart?

**Comment by maguhd** [comment] 2020-04-05 18:12
The issue is there after restarting the game, clearing cache several times.

**Comment by InZidiuZ** [comment] 2020-04-05 18:27
It became a global thing for everyone. Just restarted the inventories, and seems to have temporarily resolved the issue. Added a ton of debugging wherever I could, so just waiting for it to break again so I can further investigate it.

**Comment by MPar22** [comment] 2020-04-06 15:54
The restart fixed property storage for me, and I have had no problems with it ever since. So far so good; keep up the good work. 💪🏼

**Comment by InZidiuZ** [comment] 2020-04-11 20:46
Additional fixes and improvements have been made to the inventory-system in the past few days, all which will soon hit the live server. I'm yet to find a clear cause for this issue, but the issue might be resolved by some of the other fixes. We'll have to see. Will leave this issue open, and if you (or anyone else) encounter this issue again, please message me directly on discord so I can come investigate it.

**Comment by InZidiuZ** [comment] 2020-06-20 17:55
This issue is believed to have been resolved with 2.5.

**Closed by InZidiuZ** 2020-06-20 17:55 UTC
Labels: bug, feedback/discussion needed
