### ISSUE TITLE
[jobs/dealership] PDM Car Glitch

### ISSUE THREAD

**Issue by Mayank12345007** [InZidiuZ/op-framework-issue-tracker#1073] opened 2020-05-28 13:04 UTC
**Reporter:**
Name-Lycan Babu
Steam id-https://steamcommunity.com/profiles/76561198356104896/
Steam 3 hex id-1100001179806c0
Discord id-Pro Gaming#6989

**Summary:**
I purchased a pdm lambo car(Reaper) which cost me 60k dollers on finance.after purchasing the vehicle i stored the car in garage c.then my game crashed then i rejoined the city to check my car.then i saw that my reaper car replaced with granger.please help me my 60k money got detucted.i want my money back.

**Steps to Reproduce:**
1-purchased reaper car
2-stored in garage c
3-game crashed then rejoined the city
4-reaper car replaced with granger 

**Expected Results:**
Car should be Reaper

**Actual Results:**
Reaper car replaced with granger

## Additional Information
i have video proof of this situation
https://drive.google.com/file/d/1aCah2W9TfB6fSO6QQ3QQE1uIsFpvuwt2/view?usp=drivesdk

**Screenshots:**
i already gave video proof.

**Game Resolution:**
1600 into 900

**Player Data:**
In game name Lycan Babu
Character id-8308

**Server:**
India server

**Notes:**
please give my money back

**Comment by InZidiuZ** [comment] 2020-06-21 15:34
Not able to reproduce this locally. Gonna guess a PDM worker replaced the vehicle on another server just as you purchased it. Therefore this will remain a wontfix until the PDM system rewritten. I'd suggest having a PDM worker present as you purchase any vehicle.

**Closed by InZidiuZ** 2020-06-21 15:34 UTC
Labels: bug
