### ISSUE TITLE
Suggestion - Anonymous Banks

### ISSUE THREAD

**Issue by txxlrrsCoding** [InZidiuZ/op-framework-issue-tracker#3039] opened 2023-11-20 13:27 UTC
### Assurance

I have read the `README.md`

### Summary

Add a way for WL gangs to have their own bank account in which club funds will be held, and certain members can have access to.
It would be a whole different provider, not maze bank. Something like DarkFunds or idk? But you get the idea. Instead of one person handling all of the money, give us a shared account and like with group properties, give each person a different level of access.
For example:

Hangaround - No access at all
Prospect - View and Donate
Member - View and Donate
Low Table - View, Donate, REQUEST funds
High Table - View, Donate, Take Funds

Also add logs so we can track who did what.

### Reason

This would be good, because instead of one person who has to handle all of the group's money and keep it separate from their personal money, we can handle it all through the app. For example, if AOD were to host an event, I could put in a request for 100k from club funds to host it and pay for all the necessary things.
We can see who has donated, how much, when, maybe even why?
We can see who took money, how much, when, why?
A lot of possibilites that would save a lot of times with shipments and other things which require money.

**Comment by coalaura** [comment] 2023-11-20 15:12
duplicate of #2852

**Closed** 2023-11-20 15:12 UTC
Labels: suggestion
