### ISSUE TITLE
Suggestion - Boombox looping feature & playlists

### ISSUE THREAD

**Issue by Alyshiva** [InZidiuZ/op-framework-issue-tracker#2949] opened 2023-09-10 06:29 UTC
### Assurance

I have read the `README.md`

### Summary

Can there be a way to loop the playlist you make on boomboxes so you can load a bunch of songs and be done with it rather than constantly having to add more songs. Or be able to link playlists from YouTube rather than just videos

### Reason

Everyone I have talked to in city has been really excited by this idea as it takes some of the tediousness out of playing music, and also it brings more realism to the city since you can loop playlists on almost every music platform available in the real world.

**Comment by coalaura** [comment] 2023-11-04 15:14
Duplicate of #2534

**Closed by coalaura** 2023-11-04 15:14 UTC
Labels: suggestion
