### ISSUE TITLE
Metal detectors

### ISSUE THREAD

**Issue by SluggsV2** [InZidiuZ/op-framework-issue-tracker#3301] opened 2024-03-28 18:32 UTC
### Assurance

I have read the `README.md`

### Summary

A item that can purchased from any hardware store

### Reason

This would be used by anyone that wants to use it, would be another job like hunting, mining, and diving

Metal detector - Used at beach’s and or parks

Maybe the loot pools can be,  rings, coins, scrap, aluminum, cans, bottles, phones, watches and different things of all value, even the chance at getting “You found nothing” 

it would be a huge change you would have to walk up and down the beach and every so often it would say, “Click E To Metal Detect” and then it would have a loot pool, fully randomly odds at finding it at sandy locations tho!

**Comment by HollaYalla** [comment] 2024-03-28 18:43
This is similar to #2775

**Comment by coalaura** [comment] 2024-03-28 21:09
duplicate of #2775

**Closed by coalaura** 2024-03-28 21:09 UTC
Labels: suggestion
