### ISSUE TITLE
Public Phone

### ISSUE THREAD

**Issue by ilSensei** [InZidiuZ/op-framework-issue-tracker#2832] opened 2023-06-08 17:41 UTC
### Assurance

I have read the `README.md`

### Summary

![image](https://github.com/InZidiuZ/op-framework-issue-tracker/assets/47145680/c778d87d-faef-47d6-a240-edf27dd3a0dd)

Will be cool if this prop here can have interact like as public phone that you can call from there as static call (Anonymous call) .

### Reason

people can easily call friends if they don't have phone in the inventory, for my opinion it will be a good update

**Comment by coalaura** [comment] 2023-06-08 19:53
duplicate of #2286

**Closed by coalaura** 2023-06-08 19:53 UTC
Labels: suggestion
