### ISSUE TITLE
Suggestion - refillable jerry cans

### ISSUE THREAD

**Issue by merrick453** [InZidiuZ/op-framework-issue-tracker#2933] opened 2023-08-27 17:02 UTC
### Assurance

I have read the `README.md`

### Summary

just think out loud but maybe adding refillable jerry cans 

### Reason

think it would add something that no or city has

**Comment by merrick453** [comment] 2023-08-27 17:03
meant no other city has

**Comment by coalaura** [comment] 2023-08-28 19:11
duplicate of #2615

**Closed by coalaura** 2023-08-28 19:11 UTC
Labels: suggestion
