### ISSUE TITLE
Hotwired boat won't move

### ISSUE THREAD

**Issue by jokersleuth** [InZidiuZ/op-framework-issue-tracker#163] opened 2019-07-04 17:28 UTC
I hotwired a boat successfully, but the boat won't move. It only inches forward extremely slowly,  to the sides, but won't back up. Fuel is full and everything, but the boat won't move at the actual speed

**Comment by InZidiuZ** [comment] 2019-07-05 16:05
Closing this as the template was used, also not able to reproduce it.

**Closed by InZidiuZ** 2019-07-05 16:05 UTC
Labels: bug
