### ISSUE TITLE
Suggestion - Ability to break handcuffs

### ISSUE THREAD

**Issue by Psycho1952** [InZidiuZ/op-framework-issue-tracker#3538] opened 2024-09-04 23:47 UTC
### Assurance

I have read the `README.md`

### Summary

Since you guys can now add minigames/hacks it would be very nice now to add a breaking cuff ability like lockpicking is atm.Little skill check just to press E at the certain time to be able to breakcuffs.The idea is to give them 3-4 tries to break cuffs but each time its faster and faster to press E to breakcuffs.If they fail to breakcuffs they get instantly Hardcuffed.

### Reason

Reason to this is it would reduce malding rate and  people being mad for getting cuffed.It also removes the awkwardness of handcuffing someone and then reading them their rights and "stalling" so they can try and lockpick their cuffs.It alsmo removes awkwardness if mid searching the suspect they lockpick cuffs and start running.But also its a skill check if they dont manage to break cuffs they get hard cuffed and they cant be mad now because its on them for not being able to break cuffs. This also possibly gives people more confidence to do more crime since it has been dry latley.

**Comment by coalaura** [comment] 2024-09-04 23:49
I don't really like the idea of being able to do it instantly, however reducing the lockpicking time and adding that or another minigame into it could be fun

**Comment by Psycho1952** [comment] 2024-09-04 23:54
Okay i understand but we are still sitting at this awkwardness of "waiting" for them to lockpick or having a minigame added its just idk makes no sense for me. Beacause some people will instantly go search take lockpick or move the other person so it stops their lockpicking.Ability to break cuffs makes more sense because then they are ressisting but also breaking cuffs takes "precision" because rn u cuff a person and thats it game over.

**Comment by SluggsV2** [comment] 2024-09-04 23:54
I don’t think decreasing the time will do much, I think there should be a chance at not getting handcuffed (for example the minigames) 

when a cop or crim uses handcuffs on you, it’ll pop up a mini game you gotta solve

**Comment by joevapes3** [comment] 2024-09-05 00:15
this is a great idea, with the implementation of mini games it should definitely be considered, and it would change breaking cuffs from lockpick based to skill based. Use the same mini game from the car hotwiring script has now, and make 3 press E's come in succession back to back as soon as someone is handcuffed and they got to hit all 3 to break cuffs, and then each time they break the cuffs the speed increases on the minigame and by the 3rd or 4th time be almost impossible to break. That way you realistically can only break cuffs about 2-3 times depending on skill. I think this get rid of the race that some officers do to remove lockpicks. I personally don't do that, but I do see it happen and it would eliminate that and that's worth it in itself.

This change would be huge for crim and cop rp, it would make arresting someone a bit more difficult but it will also have more of a chance to extend their rp. Have a cooldown on the player for 30 minuets so that if they're cuffed again within 30 minuets it that they are at the same skill level they were at previously. After that have it 0 out and go back to the slowest speed. 

Anyways my thoughts on this :)

**Comment by coalaura** [comment] 2024-09-05 12:13
> Okay i understand but we are still sitting at this awkwardness of "waiting" for them to lockpick or having a minigame added its just idk makes no sense for me. Beacause some people will instantly go search take lockpick or move the other person so it stops their lockpicking.Ability to break cuffs makes more sense because then they are ressisting but also breaking cuffs takes "precision" because rn u cuff a person and thats it game over. So bassically when i do HC while im doing my cuffs animation that person gets a mini game to press E on a minigame to ressist and break cuffs.

You would no longer be "waiting" for them. I'm suggesting either making the time much lower so you don't have to wait for them, or making it a (somewhat difficult) minigame so it would be skill based. In both cases it would reduce the time to lockpick by A LOT making it so you don't have to "wait" on them. But it also leaves you the ability to take their lockpick to prevent them from doing it. I just see a lot of issues arising with giving people the ability to just break out of cuffs just like that without any item or smth.

**Comment by coalaura** [comment] 2024-09-05 12:15
Going to close this as its a duplicate of #2228 but feel free to continue the conversation in the original issue :)

**Closed by coalaura** 2024-09-05 12:15 UTC
Labels: suggestion
