### ISSUE TITLE
Suggestion - Shared Luxury Autos Garage 

### ISSUE THREAD

**Issue by darkness511** [InZidiuZ/op-framework-issue-tracker#3335] opened 2024-04-17 18:18 UTC
### Assurance

I have read the `README.md`

### Summary

Allow LA Owner to give access to Salesman/Employee to have access to Luxury Autos garage and be able to pull vehicles out and sell it.
Since we have limited 5-7 Employees and we face issues as cant show all cars in stock.
similar to recent #3332 & already mentioned in #2859 but made knew suggestion as it was outdated.

### Reason

Quality of business, As we sell **Pre-Owned Cars**, it makes easier to sell cars as not everyone is available all the time, 
for example. Currently the only way whoever has stock has to fly in, physically transfer the car over.
If this happens then the quality of RP increases as we can show and sell the stocks we have.

**Comment by coalaura** [comment] 2024-04-17 22:35
the suggestion is still open that means its still on the todo list, opening a new suggestion with the same content will not move you up on the todo list.

closing as duplicate of #2859

**Closed by coalaura** 2024-04-17 22:35 UTC
Labels: suggestion
