### ISSUE TITLE
Bug report - Shooting automatics from vans

### ISSUE THREAD

**Issue by King2704** [InZidiuZ/op-framework-issue-tracker#2971] opened 2023-10-07 07:23 UTC
### Assurance

I have read the `README.md`

### Reporter

stargroot

### Summary

You used to be able to use automatic weapons in the back seat of vans until the use of automatic weapons got disabled. This also means you cant use them in the back seats of vans anymore. The use of automatics in those cars should get enabled again since the purpose of those cars is to be able to use big weapons with less cover/higher risk. 

### Steps to Reproduce

Get in a van with an automatic gun
switch to the seat that should let you use it
ads (cant do that)

### Expected Behavior

Get in a van with an automatic gun
switch to the seat that should let you use it
ads (can do that)

### Actual Results

Get in a van with an automatic gun
switch to the seat that should let you use it
ads (cant do that)

### Server

International (c3s1.op-framework.com)

**Comment by coalaura** [comment] 2023-10-07 15:37
Duplicate of #2652

**Closed by coalaura** 2023-10-07 15:37 UTC
Labels: bug
