### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by EVILKTM** [InZidiuZ/op-framework-issue-tracker#514] opened 2019-10-12 00:46 UTC
Seth 
KTM#0661

Summary
My suggestion is about the vehicle keys. Well all have been there where we have like 10 or 15 keys in are inventorys and it gets pretty stupid and i would like you to add where if you get the keys to your vehicle you get the keys but there are no keys in your inventory so for example kinda like the PD weapons right now if you go in and get the weapons you dont have them in your inventory but you have them and it would be like that when you pull out a vehicle or if you hot wire a vehicle you get the keys also. So over all i just want where if you get the keys to vehicles you get them on you but not in your inventory and you could also add where you do /givekeys so your friends can have the keys also just for your car

**Reason:**
My reason is because im always having 10 keys in my inventory and its really dumb and it would make my life a lot easyer

**Comment by InZidiuZ** [comment] 2019-10-15 12:51
Duplicate of #515, so closing.

**Closed by InZidiuZ** 2019-10-15 12:51 UTC
Labels: enhancement
