### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by scarblaz** [InZidiuZ/op-framework-issue-tracker#816] opened 2020-02-18 06:43 UTC
**Reporter:**
Scarblaz (ScArbLaZ#7104) (https://steamcommunity.com/id/scarblaz/)

**Summary:**
after the wipe bugs like FPS issues,cant see few players and their cars like i booked a taxi yesterday and i can see him but not his taxi and other car but not the driver ( real player)

**Steps to Reproduce:**
FIX FPS ISSUES,BUGS TWEAK THE SERVER

**Expected Results:**
no fps issues and no invisible bugs
#815 

**Actual Results:**

## Additional Information

**Screenshots:**
unfortunately screenshots are not there.

**Game Resolution:**
normal game 16:9 but in fivem 1024x768 (due to fps drops)

**Player Data:**
Scarblaz,dob:02/04/1999

**Server:**
INDIA LEGACY ROLEPLAY server 

**Notes:**
For anything else noteworthy.

**Comment by iGreatWhite** [comment] 2020-02-18 07:14
Those are not steps to reproduce this issue. Which is caused by onesync btw. Not much InZidiuZ can do right now about it.

**Comment by InZidiuZ** [comment] 2020-02-18 07:41
Hey,

This is unrelated to the framework, so closing.

**InZidiuZ**
*OP-FW Developer*

**Closed by InZidiuZ** 2020-02-18 07:41 UTC
Labels: bug
